{{- $altNames := list ( "resource-group-controller.resource-group-controller.svc" ) -}}
{{- $ca := genCA "coaster" 365 -}}
{{- $cert := genSignedCert "resource-group-controller" nil $altNames 365 $ca -}}


apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resource-group-controller.resource-group.ten1010.io
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: resource-group-controller.resource-group.ten1010.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc | quote }}
      service:
        namespace: {{ .Release.Namespace }}
        name: resource-group-controller
        path: /admissionreviews
        port: 8080
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods", "replicationcontrollers" ]
        scope: "*"
      - apiGroups: [ "batch" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "cronjobs", "jobs" ]
        scope: "*"
      - apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "daemonsets", "deployments", "replicasets", "statefulsets" ]
        scope: "*"
    sideEffects: None
    timeoutSeconds: 10
---

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: resource-group-controller-tls
  namespace: {{ .Release.Namespace }}

data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}