namespace: resource-group-controller
configMapGenerator:
  - name: resource-group-controller-envs
    literals:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=production
      - LOGGING_LEVEL_IO_TEN1010_COASTER_GROUPCONTROLLER=info
      - SERVER_SSL_CERTIFICATE=/etc/resource-group-controller/tls/tls.crt
      - SERVER_SSL_CERTIFICATE_PRIVATE_KEY=/etc/resource-group-controller/tls/tls.key
      - SERVER_SSL_TRUST_CERTIFICATE=/etc/resource-group-controller/tls/ca.crt
secretGenerator:
  - name: resource-group-controller-tls
    files:
      - tls.crt
      - tls.key
      - ca.crt
generatorOptions:
  disableNameSuffixHash: true
resources:
  - templates/namespace.yaml
  - templates/service-account.yaml
  - templates/cluster-role.yaml
  - templates/crd.yaml
  - templates/deployment.yaml
  - templates/service.yaml
  - templates/mutating-webhook-configuration.yaml
patchesStrategicMerge:
  - patches.yaml
